apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
    # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://headlamp-k8s.github.io/headlamp/
    chart: headlamp
    targetRevision: 0.26.0
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true