apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/i-Sight/argocd-config.git
        revision: HEAD
        directories:
          - path: cluster-addons/*
  template:
    metadata:
      # name: '{{.path.basename}}-application'
      name: '{{.path.basename}}'
      # Add a this finalizer ONLY if you want these to cascade delete.
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/i-Sight/argocd-config.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true